### ISSUE TITLE
Cannot install some Wally packages on Linux

### ISSUE THREAD

**Issue by SolarHorizon** [pesde-pkg/tooling#2]
When using pesde with Wally packages on Linux, dependency resolution will sometimes hang infinitely. I don't have this issue on Windows and I don't have a MacOS machine to test on.

I am able to consistently reproduce this issue when trying to install `wally#jsdotlua/react-roblox` on Linux.

For a minimal repro:
```toml
name = "test/dependency_resolution"
version = "0.1.0"

[target]
environment = "roblox"

[indices]
default = "https://github.com/pesde-pkg/index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.1.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.4.4", target = "lune" }

[dependencies]
react-roblox = { wally = "wally#jsdotlua/react-roblox", version = "^17.2.1" }
```

**Comment by CompeyDev** [comment]
In my testing, I don't see this happen anymore, I think it might have been fixed. Can you try on your end again?

**Comment by SolarHorizon** [comment]
I'm still not able to install the package (jsdotlua/react, specifically). I don't think the issue was related to compression in the first place because Rojo & other pesde managed tools were working fine when running them on their own, they just don't seem to work properly when pesde tries to run them through a script, like the sourcemap generator script.

When running `pesde install` using Rojo managed by pesde, even after verifying that Rojo works properly on its own (i.e. when running it myself), my CPU jumps to 100% usage and there are tons of processes left running. All of these processes are from pesde trying to run the sourcemap generator script, but it gets stuck at some point and never finishes, causing the install command to hang indefinitely.

**Comment by CompeyDev** [comment]
> I don't think the issue was related to compression in the first place because Rojo & other pesde managed tools were working fine when running them on their own, they just don't seem to work properly when pesde tries to run them through a script, like the sourcemap generator script.

I believed so because this seems to occur when we have multiple simultaneous versions of pesde managed Rojo that are spawned, causing multiple `unzip` commands trying to install / write to the same path where some might succeed before others, leading to a race condition. 

I'll try to debug further, this is a bit odd since I wasn't able to reproduce this after swapping over to the library.

**Comment by CompeyDev** [comment]
Someone else also ran into the same issue and I was able to further debug it -- it looks like a race condition to do with concurrent resource accesses when multiple processes of uncached tooling packages try to install at the same time. 

To attempt to fix this, I have added a locking mechanism to the installation process, starting at commit https://github.com/pesde-pkg/tooling/commit/295023129f0417f705d3e89a60553c566538d2c2, spanning over the next few commits further refining its implementation.

I will also attempt to try to reproduce this bug with these changes.

**Comment by CompeyDev** [comment]
I have released [toolchainlib@v0.1.10](https://github.com/pesde-pkg/tooling/blob/f99a4f787d45cf944ef504120d060e4f8a50cd1e/CHANGELOG.md#0110---2025-01-22), please try reproducing this again.

**Comment by CompeyDev** [comment]
These changes have been published as a part of [v0.1.12](https://pesde.dev/packages/pesde/toolchainlib/0.1.12/any), and with testing on my end, seems to have been fixed on Linux. Please let me know if this has been fixed for you too on Linux and Windows.

Run `pesde update` to get the latest version of toolchainlib in your project.

**Comment by CompeyDev** [comment]
Closing because it cannot be replicated in testing anymore. Reopen if you face the issue again.
